name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - xarray
  - cartopy
  - scipy
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
